### ISSUE TITLE
Implement assignment_candidate.sort

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#28]

**Comment by normanjaeckel** [comment]
I think assignment .can_manage is required (but the respecitve meeting of course),

**Comment by ostcar** [comment]
@normanjaeckel  Please fix this in the backend. If only one permission check is required, then a `Generic permission check` is possible. See https://github.com/OpenSlides/openslides-backend/pull/370

**Comment by normanjaeckel** [comment]
Will be done with https://github.com/OpenSlides/openslides-backend/pull/380

**Comment by ostcar** [comment]
I reopen this as a reminder, that I have to regenerate the generic actions

**Comment by normanjaeckel** [comment]
Please check this. We do not have any backend permission strings now.

**Comment by ostcar** [comment]
Would it be possible for you to rename the action to `assignment.sort` and change the payload value `assignment_id` to `id`?

I think this is better because the action does not sort one candidate. It sorts (the candidates of) an assignment.

It would help me, because I have generic code to handel an action with the name `COLLECTION.action` when there is the field `id` in the payload that is the id of `COLLECTION`.

**Comment by ostcar** [comment]
I would like to keep you assigned until you (and you backend team) gave me an answer.

**Comment by normanjaeckel** [comment]
I think I can not do anything here until the question in reference issue is solved.

**Comment by ostcar** [comment]
@FinnStutzenstein Is this action already implemented by the backend? Can we close this issue here?
