### ISSUE TITLE
Implement motion.update

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#39]

**Comment by normanjaeckel** [comment]
Managers with motion.can_manage can do everything.

Submitters (with allow_submitter_edit enabled, see #37) can change title, text, reason and amendment_paragraphs. In this case we must eventually clear supporters. Maybe just send `clearingSupportersPossiblyRequired: true`

**Comment by ostcar** [comment]
@FinnStutzenstein Is this the only case where additionalData is needed? Maybe we can find another solution for it? For example, we could make two actions out of it (or a flag inside the data).

```
1. motion.update_clearing_supporters
2. motion.update_without_clearing_supporters
```

**Comment by FinnStutzenstein** [comment]
I think it is currently the only case, yes. But splitting the update actions into two actions or add additional properties in the client (you've proposed clear_supporter) is not good since the client should not know about this. This should not be a big problem since it can be well tested as well as the code for additional data is (was?) there, so IMO we should keep it. Also, maybe we get new cases where we need it, so we have the capability already implemented.

**Comment by normanjaeckel** [comment]
Submitters can not edit motions they can not see according to state restrictions.

**Comment by normanjaeckel** [comment]
Also care about supporters. Only with `motion.can_support` you can make yourself as supporter.

**Comment by ostcar** [comment]
@normanjaeckel I don't understand this action. Please talk about it via telephone.

**Comment by normanjaeckel** [comment]
Please recheck this action. We want to add some new fields that are for managers only.

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend-coordination/issues/25

**Comment by ostcar** [comment]
I don't understand it

**Comment by normanjaeckel** [comment]
The payload will change soon and then the permission service should be double checked that the action works correctly. Maybe there is not much work.

**Comment by ostcar** [comment]
@FinnStutzenstein Is this action already implemented by the backend? Can we close this issue here?
